name: DartTemplate
author: Sergio Lisan, Krishna Raman
version: 2.0.0
homepage: https://github.com/venosyd/openshift-dart
description: Template Dart application for OpenShift Dart cartridge
dependencies:
  browser: any
  polymer: any
  stream: any
